class AppLocalizations {
  static String locale = 'en';

  static const Map<String, Map<String, String>> _dict = {
    'en': {
      'dashboard': 'Dashboard',
      'explore': 'Explore',
      'feed': 'Feed',
      'profile': 'Profile',
      'settings': 'Settings',
      'new_routine': 'New Routine',
      'workout_completed': 'Workout Completed',
      'liked_exercises': 'Liked Exercises',
      'fitness_goal': 'Fitness Goal',
      'weight_loss': 'Weight Loss',
      'conditioning': 'General Conditioning',
      'bodybuilding': 'Advanced Bodybuilding',
      'logout': 'Logout',
      'save': 'Save',
      'all_exercises': 'All Exercises',
      'custom_routines': 'Custom Routines',
      'fitness_test': 'Fitness Test',
      'search_exercises': 'Search exercises...',
      'all': 'All',
      'no_exercises_found': 'No exercises found',
      'no_posts_yet': 'No posts yet.',
      'guest': 'Guest',
      'day_streak': 'Day Streak',
      'first_step': 'First Step',
      'consistency': 'Consistency',
      'power': 'Power',
      'night_owl': 'Night Owl',
      'workouts': 'Workouts',
      'minutes': 'Minutes',
      'avg_mins': 'Avg Mins',
      'recent_activity': 'Recent Activity (Minutes)',
      'fitness_diagnostic': 'Fitness Diagnostic',
      'perform': 'Perform',
      'submit': 'Submit',
      'hello': 'Hello, ',
      'athlete_greeting': 'Athlete',
      'plan': 'Plan',
      'today_workout': 'Today\'s Workout',
      'tap_to_start': ' completed · Tap to start',
      'setup_instructions': 'Setup your profile to begin tracking workouts.',
      'exercises_count': ' exercises',
      'track_progress': 'Track Your Progress',
      'track_progress_sub': 'Set goals and follow your fitness journey every day.',
      'next': 'Next',
      'start_today': 'Start Today',
      'start_today_sub': 'Thousands of exercises. One app.',
      'get_started': 'Get Started',
      'what_is_goal': 'What is your main goal?',
      'weight_loss_title': '🔥 Weight Loss',
      'weight_loss_sub': 'Burn fat and get lean',
      'conditioning_title': '🏃 Conditioning',
      'conditioning_sub': 'Improve stamina and athletic performance',
      'bodybuilding_title': '💪 Bodybuilding',
      'bodybuilding_sub': 'Build muscle mass and strength',
      'continue_btn': 'Continue',
      'start_workout': 'Start Workout',
      'rest': 'REST',
      'finish_workout': 'Finish Workout',
      'set_complete': 'Set Complete ✓',
      'skip_rest': 'Skip Rest →',
      'set': 'Set',
      'of': ' of ',
      'duration': 'Duration',
      'duration_30s': '30 sec',
      'reps': 'Reps',
      'weight': 'Weight',
      'exit_workout': 'Exit Workout?',
      'exit_workout_sub': 'Your progress will not be saved.',
      'keep_going': 'Keep Going',
      'exit': 'Exit',
      'workout_complete': 'Workout Complete!',
      'duration_label': 'Duration: ',
      'minutes_suffix': ' minutes',
      'volume_lifted': 'Volume Lifted: ',
      'kg_suffix': ' kg',
      'share_to_feed': 'Share to Feed',
      'workout_shared': 'Workout shared to feed!',
      'close_summary': 'Close Summary',
      'target': 'Target',
      'equipment': 'Equipment',
      'level': 'Level',
      'exercise_images': 'Exercise Images',
      'description': 'Description',
      'how_to_perform': 'How to Perform',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'no_account': 'Don\'t have an account? Register',
      'have_account': 'Already have an account? Login',
      'incomplete_profile': 'You have no workout plan yet — complete your health profile to get recommendations.',
      'complete_now': 'Complete Profile',
    },
    'vi': {
      'dashboard': 'Bảng Điều Khiển',
      'explore': 'Khám Phá',
      'feed': 'Cộng Đồng',
      'profile': 'Hồ Sơ',
      'settings': 'Cài Đặt',
      'new_routine': 'Lịch Tập Mới',
      'workout_completed': 'Hoàn Thành Bài Tập',
      'liked_exercises': 'Bài Tập Yêu Thích',
      'fitness_goal': 'Mục Tiêu Thể Hình',
      'weight_loss': 'Giảm Cân',
      'conditioning': 'Thế Lực Tổng Hợp',
      'bodybuilding': 'Tăng Cơ Chuyên Sâu',
      'logout': 'Đăng Xuất',
      'save': 'Lưu',
      'all_exercises': 'Tất Cả Bài Tập',
      'custom_routines': 'Lịch Tập Tự Tạo',
      'fitness_test': 'Kiểm Tra Thể Lực',
      'search_exercises': 'Tìm kiếm bài tập...',
      'all': 'Tất Cả',
      'no_exercises_found': 'Không tìm thấy bài tập',
      'no_posts_yet': 'Chưa có bài đăng nào.',
      'guest': 'Khách',
      'day_streak': 'Ngày Liên Tiếp',
      'first_step': 'Bước Đầu Tiên',
      'consistency': 'Kiên Trì',
      'power': 'Sức Mạnh',
      'night_owl': 'Cú Đêm',
      'workouts': 'Lần Tập',
      'minutes': 'Số Phút',
      'avg_mins': 'Phút/Lần',
      'recent_activity': 'Hoạt động gần đây (Phút)',
      'fitness_diagnostic': 'Chẩn Đoán Thể Lực',
      'perform': 'Thực Hiện',
      'submit': 'Xác Nhận',
      'hello': 'Xin chào, ',
      'athlete_greeting': 'Vận Động Viên',
      'plan': 'Kế Hoạch',
      'today_workout': 'Bài Tập Hôm Nay',
      'tap_to_start': ' đã hoàn thành · Chạm để bắt đầu',
      'setup_instructions': 'Thiết lập hồ sơ để bắt đầu theo dõi tập luyện.',
      'exercises_count': ' bài tập',
      'track_progress': 'Theo Dõi Tiến Độ',
      'track_progress_sub': 'Đặt mục tiêu và theo dõi hành trình mỗi ngày.',
      'next': 'Tiếp Theo',
      'start_today': 'Bắt Đầu Ngay',
      'start_today_sub': 'Hàng ngàn bài tập. Một ứng dụng duy nhất.',
      'get_started': 'Bắt Đầu',
      'what_is_goal': 'Mục tiêu chính của bạn là gì?',
      'weight_loss_title': '🔥 Giảm Cân',
      'weight_loss_sub': 'Đốt mỡ và thon gọn',
      'conditioning_title': '🏃 Thể Lực',
      'conditioning_sub': 'Cải thiện sức bền và hiệu suất',
      'bodybuilding_title': '💪 Tăng Cơ',
      'bodybuilding_sub': 'Xây dựng cơ bắp và sức mạnh',
      'continue_btn': 'Tiếp Tục',
      'start_workout': 'Bắt Đầu Tập',
      'rest': 'NGHỈ',
      'finish_workout': 'Kết Thúc Bài Tập',
      'set_complete': 'Hoàn Thành Hiệp ✓',
      'skip_rest': 'Bỏ Qua Nghỉ →',
      'set': 'Hiệp',
      'of': ' / ',
      'duration': 'Thời Gian',
      'duration_30s': '30 giây',
      'reps': 'Số Lần',
      'weight': 'Trọng Lượng',
      'exit_workout': 'Thoát bài tập?',
      'exit_workout_sub': 'Tiến độ của bạn sẽ không được lưu.',
      'keep_going': 'Tiếp Tục',
      'exit': 'Thoát',
      'workout_complete': 'Hoàn Thành Bài Tập!',
      'duration_label': 'Thời gian: ',
      'minutes_suffix': ' phút',
      'volume_lifted': 'Tổng Khối Lượng: ',
      'kg_suffix': ' kg',
      'share_to_feed': 'Chia Sẻ Lên Cộng Đồng',
      'workout_shared': 'Đã chia sẻ bài tập!',
      'close_summary': 'Đóng Tóm Tắt',
      'target': 'Nhóm Cơ',
      'equipment': 'Thiết Bị',
      'level': 'Cấp Độ',
      'exercise_images': 'Hình Ảnh Bài Tập',
      'description': 'Mô Tả',
      'how_to_perform': 'Cách Thực Hiện',
      'login': 'Đăng Nhập',
      'register': 'Đăng Ký',
      'email': 'Email',
      'password': 'Mật khẩu',
      'no_account': 'Chưa có tài khoản? Đăng ký',
      'have_account': 'Đã có tài khoản? Đăng nhập',
      'incomplete_profile': 'Bạn chưa có kế hoạch tập luyện — hoàn thiện hồ sơ sức khỏe để nhận gợi ý phù hợp.',
      'complete_now': 'Hoàn thiện hồ sơ',
    }
  };

  static String get(String key) {
    return _dict[locale]?[key] ?? _dict['en']?[key] ?? key;
  }
}
